### ISSUE TITLE
must create project in $GOPATH/src

### ISSUE THREAD

**Issue by spaceywolfi** [fragmenta/fragmenta#23]
```
19:53:38 You must create your project in $GOPATH/src
```
why does it have to be in that folder? Its not a big issue, but i would still prefare being able to create a project in any directory.

**Comment by kennygrant** [comment]
Unfortunately the go tools simply don't work if you're not in GOPATH (or didn't last time I checked, things like tests failed). I may however change this to just a warning, as it can be annoying. I will try testing that out.

**Comment by kennygrant** [comment]
After some thought, what I'd like to do is remove this restriction and instead add a warning, so that we're prepared for a future in which the go team change the tools to let you work anywhere. I understand they've made some progress on that already. I will test that out and commit, or if you prefer, happy to take a pull request.
