### ISSUE TITLE
Enhancement: Kill server process using PID (platform agnostic)

### ISSUE THREAD

**Issue by th3coop** [fragmenta/fragmenta#24]
- Write cmd.Process.PID to a file like `.running` when server is started
- in `killServer`:
   - check file exists
   - get pid from file
   - p := os.Process.FindProcess(pid)
  - p.Kill()

Side note: I have at least two PRs incoming.  One would address this if. The other fixes some other platform agnosticities (yes that's a made up word).

**Comment by kennygrant** [comment]
This sounds good to me, since this tool is just used to run the server locally, ideally it'd work well on windows too, I'm afraid I haven't had a windows laptop to test on so the windows support has been lacking in the past. I'd prefer if the file was created in secrets as a dotfile, as that's where I tend to put stuff that shouldn't be committed to projects.

**Comment by cgchoffman** [comment]
> I'd prefer if the file was created in secrets as a dotfile, as that's where I tend to put stuff that shouldn't be committed to projects.

Agreed.
