### ISSUE TITLE
Fragmenta cmd should not ignore invalid arguments

### ISSUE THREAD

**Issue by GeertJohan** [fragmenta/fragmenta#27]
It can be very confusing when `fragmenta` runs without an error even though there are invalid arguments.

I believe it would be beneficial to the cmd to start using a cli framework such as https://github.com/jawher/mow.cli

This will make development on the CLI easier and different developers working on fragmenta will have to adhere to the same CLI structure when proposing changes.
I would be happy to create a PR which converts the existing structure to `mow.cli`.

**Comment by kennygrant** [comment]
I’m happy to consider suggestions for different behaviour (for example it should perhaps only run a server if it has zero arguments, not typos). I agree this should be fixed. I’ll leave this issue open for that. The fix would be relatively simple. 

I don’t want to add another dependency though, and don’t think it would add much in this case. The aim is zero external dependencies.

**Comment by GeertJohan** [comment]
Why would you not want to add dependencies? A package to handle flags would add just that: properly handling arguments (commands and flags).

**Comment by kennygrant** [comment]
> Why would you not want to add dependencies? A package to handle arguments would add just that: properly handling arguments (commands and flags).

Because a small dependency graph is a good thing. I don't think a large change is required here though to get the behaviour you want (which I agree with), it's a one line change, and I prefer the simpler code in the app at present to importing another dependency as I don't anticipate changing commands much. This is a small tool to help build, run and deploy apps and I'd like to keep the surface area as small as possible. 

So on to the problem:

At present, fragmenta runs the server _when run with no commands_  *if* you're in a valid project directory - I'd like to keep that as it's a useful shortcut which I use all the time, _however_ it should not run the server when invalid arguments are given (the problem you have experienced). I've seen this myself a couple of times with a typo and would like to fix it. 

So the simple fix is simply to check on line 127 if command == "" and only run the server in that case, happy to accept a pull request for that or I can put it in.
